### PR TITLE
Jaydenn (Ching-Ting) Chang --- Module2 Activity

### PR DESCRIPTION
**Pull request by dennx2**

### CODE REVIEW

**Comment by OleksiiKachan** [comment]
I can't grade as you did not submit it on the blackboard. submit the link there, so I can put the grade

**Comment by dennx2** [comment]
Hello,

Here is the link: https://github.com/OleksiiKachan/xml-and-js/pull/28

Sorry about that.


*Jaydenn Chang (she/her)*
***@***.***

**Comment by OleksiiKachan** [comment]
blackboard. not github

**Comment by dennx2** [comment]
Done!

*Jaydenn Chang (she/her)*
***@***.***

**Pull request closed without merging**
